[package]
name = "cf-dns-record-update"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
cloudflare = "0.9.1"
env_logger = "0.9.0"
log = "0.4.0"
openssl = { version = "0.10.38", features = ["vendored"] }
serde = { version = "1.0.133" }
serde_json = "1.0.74"
trust-dns-resolver = "0.20.3"
ureq = { version = "2.4.0", features = ["json"] }
