[package]
name = "cf-dns-record-update"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34"
cloudflare = "0.9.0"
failure = "0.1.8"
maplit = "1.0"
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "1.0" }
serde_json = "1.0"
trust-dns-resolver = "0.20.3"
ureq = { version = "2.4.0", features = ["json"] }
